# Generated by Django 3.2.4 on 2021-06-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanlov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='media/event_images/')),
            ],
        ),
    ]
