# Generated by Django 2.0 on 2021-07-01 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210629_1300'),
        ('mainapp', '0004_tanlov'),
    ]

    operations = [
    ]
