# Generated by Django 2.0 on 2021-07-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fakulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yunalish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('fakultet_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
